### ISSUE TITLE
[REQUEST] Enable Accelerated Networking

### ISSUE THREAD

**Issue by jbmcfarlin31** [terraform-providers/terraform-provider-azurestack#106]
I was comparing the options between azurerm and azure stack, and being involved with a support call today made me look deeper... I noticed azure stack nics have capabilities for enabling accelerated networking - but when I looked in terraform, I did not see the option.

Is this feature going to be implemented in the future? Is it already enabled?

The reference link is [here](https://www.terraform.io/docs/providers/azurerm/r/network_interface.html#enable_accelerated_networking)

Thanks!

**Comment by jbmcfarlin31** [comment]
UPDATE: 

I actually noticed this was already implemented in `azurestack/resource_arm_network_interace.go`, however it was commented out. I verified with the API profile version that supports it and the new profile does support it.

I un-commented the areas that were commented out pertaining to accelerated networking and rebuilt the binary. The binary built successfully, and upon testing it I ran into a problem pertaining to my specific azure stack location in my environment (unrelated to the binary or this code).

I am about 99% confident it will work - but standby and I will clarify when I can...
Thanks!

**Comment by jbmcfarlin31** [comment]
Well, in talking with Microsoft in regards to a separate issue, I found out that Azure Stack does not support accelerated networking as of yet. You can find a list of the differences between Azure and Azure Stack [here](https://docs.microsoft.com/en-us/azure-stack/user/azure-stack-network-differences?view=azs-1908).

My guess is it might come down the pipeline later on. This is why when trying to provision with it enabled in terraform I kept getting the error `Accelerated Networking is not Enabled for your location`.

**Comment by jbpaux** [comment]
I think we should close this issue as it's not relevant, and not en enhancement.

**Comment by jbmcfarlin31** [comment]
> I think we should close this issue as it's not relevant, and not en enhancement.

@jbpaux It would be an enhancement once azure stack adds support for it. That being said, I don't know when that would come down the pipeline (if at all). I don't understand how it is not relevant, other than it currently is not supported in azure stack.

We can close if you feel the need to and just re-open when/and if the feature comes.
