### ISSUE TITLE
Converge changes from azurerm?

### ISSUE THREAD

**Issue by pbolduc** [terraform-providers/terraform-provider-azurestack#115]
My goals in my recent contributions, is trying to update the azurestack provider to be more closely aligned with the AzureRM provider.  As mentioned in other issues, the less code that needs to be edited between the two providers allows for easier feature updates.  I would like to be able to take the data source or resource providers for the missing components and just cut stuff out that is not supported on Azure Stack. 

At this point, I am trying to make non-functional changes, that allow the two code bases to converge.  However, it can be difficult because I am not aware of the road map or priorities for the azurerm provider.  On my fork, I have an issue where I am brainstorming the changes that should be made.

- [ ] GNUmakefile changes for linting / tf linting
- [ ] ArmClient wrapping of resources in same client family (Network, Compute, ...)
   - [ ] separate packages for each client family 
- [ ] addition of internal/services

My current work contract will allow me access to a Azure Stack instance through the end of the year, possibly longer.  I would like to make headway on adding the additional resources like app service plan, app service and key vault.

Thoughts?

**Comment by sushilkm** [comment]
On the contrary, is there any possibility that we can make azurerm adaptible enough to make it work with stack instead of maintaining two code bases.

**Comment by pbolduc** [comment]
I am open to suggestions on how to approach this.  I am only a novice Go developer.  I think the different API profiles are the hardest part.   Adding **if** statements all over the place is not a maintainable approach.  The Azure provider moves a lot faster than the Azure Stack one. Suggestions?

**Comment by sushilkm** [comment]
I agree, I was thinking about it since both have similar codebases, the difference being api_url and api_version, if we can do something about reusing azurerm, that would be great, because that way, we can just reuse whatever comes to azure.

May be other maintainers of this terraform-provider can share their thoughts about how much is this feasible.

**Comment by pbolduc** [comment]
At minimum, a lot of the support classes that validate names, deal with timeouts, etc should be reusable.  For example, I noticed there is a discrepancy between the validation on a resource group name length.  In azurerm it is 90 and in azurestack it is validates to 80.  I just tested on a 1908 stack and I can create up to 90 in Azure Stack.

https://github.com/terraform-providers/terraform-provider-azurestack/blob/0f539cc7e1bc4bc745ccfc01a67cbc7d3d58e094/azurestack/resource_group_name.go#L41

![image](https://user-images.githubusercontent.com/1844480/67434153-633b9d80-f59e-11e9-871b-f94ef6a9c3be.png)

**Comment by pbolduc** [comment]
Based on the response from this issue https://github.com/terraform-providers/terraform-provider-azurerm/issues/4726  I am going to close this as well for now.  I can see the issues raised where Hashicorp is looking to add staff to help work on the Azure and Azure Stack providers.
