### ISSUE TITLE
Managed disk functionality is commented out but still in schema

### ISSUE THREAD

**Issue by paultyng** [terraform-providers/terraform-provider-azurestack#44]
https://github.com/terraform-providers/terraform-provider-azurestack/blob/e9440bae2be3e8e06a42dddacea0898271a39df7/azurestack/resource_arm_virtual_machine.go#L998-L1001

And the `vhd_uri` is probably `Required` I think if that is the case?

https://github.com/terraform-providers/terraform-provider-azurestack/blob/e9440bae2be3e8e06a42dddacea0898271a39df7/azurestack/resource_arm_virtual_machine.go#L191-L208

It does look like managed disks may be supported now? https://azure.microsoft.com/en-us/updates/managed-disks-in-azure-stack/

I'm not sure how quickly people will have that installed (include us for testing).

**Comment by martinbjorgan** [comment]
We have updated and are waiting for this as well :) 👍

**Comment by CharbelNemnom** [comment]
Any update please about Azure Stack Managed Disk with Terraform?
Thank You!

**Comment by katbyte** [comment]
@martinbjorgan & @CharbelNemnom,

There is an open PR #52 for this functionality. Its most of the way there and just needs some minor vendoring fixes IIRC.

**Comment by CharbelNemnom** [comment]
Thank you for the update, much appreciated!
Keep up the good work.
