### ISSUE TITLE
Azure Stack Storage Account features don't support some of the documented functionality

### ISSUE THREAD

**Issue by mb290** [terraform-providers/terraform-provider-azurestack#6]
Great to see that Azure Stack support is here!

I started reading through the resource documentation and there looks to be some functionality documented which I don't believe works in Azure Stack.

A document showing some of the differences are here:

[https://docs.microsoft.com/en-us/azure/azure-stack/user/azure-stack-acs-differences](https://docs.microsoft.com/en-us/azure/azure-stack/user/azure-stack-acs-differences)

For example, in the documentation there shows support for GRS etc, but in Azure Stack only LRS is supported.

Happy to do a pull request and start pairing down the functionality, but wanted to make sure y'all weren't architecting for functionality soon to be released :)

**Comment by paultyng** [comment]
@mb290 it was just an oversight that it was left in, feel free to submit the PR, and good catch :)

There will be some new resources coming relatively soon, but nothing that isn't publicly available as far as I'm aware.

**Comment by katbyte** [comment]
Hi @mb290,

As the difference you have pointed out was fixed in that PR i am going to close this issue now. Feel free to open PRs for any additional changes that need to be made 🙂
