### ISSUE TITLE
Support for Active-Active s2s VPN configuration

### ISSUE THREAD

**Issue by sGrindvoll** [terraform-providers/terraform-provider-azurestack#80]
Azurerm provider have gotten support for configuring active-active VPN connection in azurerm.virtual_network_gateway. Additionally you need two public IPs, and two ipconfiguration for the Virtual Network Gateway. 

This would allow redundant VPN connections! 

Some references for configuration with other methods: 
Powershell: https://docs.microsoft.com/en-us/azure/vpn-gateway/vpn-gateway-activeactive-rm-powershell
Terraform AzureRM: https://www.terraform.io/docs/providers/azurerm/r/virtual_network_gateway.html

**Comment by jbpaux** [comment]
According to https://docs.microsoft.com/en-us/azure-stack/user/azure-stack-network-differences Active-Active VPN are not supported (and cannot be configured) on Azure Stack.
You can close this issue as it's not one.

**Comment by katbyte** [comment]
Thanks @jbpaux, closing as suggested.
