### ISSUE TITLE
release 0.7.0, 0.8.0 of Azurestack Provider not compatible with AzureStack 1905/1906 --- wrong autorest ?

### ISSUE THREAD

**Issue by bottkars** [terraform-providers/terraform-provider-azurestack#90]
I all,
we recently moved to Azurestack 1905. i turns that some calls, specially storage, no longer work.

the error can be reproduced with the storage example 
`https://www.terraform.io/docs/providers/azurestack/r/storage_account.html`
> 
>  azurestack_storage_account.testsa: 1 error occurred:
>         * azurestack_storage_account.testsa: azurestack_storage_account.testsa: Error reading the state of AzurStack Storage Account "": storage.AccountsClient#GetProperties: Invalid input: autorest/validation: validation failed: parameter=accountName constraint=MinLength value="" details: value length must be greater than or equal to 3

**Comment by bottkars** [comment]
was tested against asdk 1905 from powershell and linux

**Comment by jbmcfarlin31** [comment]
@bottkars Currently seeing this same error, although I am running version `0.6.0` of the provider on terraform version `0.11.14`. We just recently upgraded our stack to the 1905 build also.

**Comment by LynxPantera** [comment]
Hi @bottkars, @jbmcfarlin31,
I also have the same problem with the new version 1905 build, I did the tests with Terraform `0.12.2` and the provider version `0.7.0`.

**Comment by jbpaux** [comment]
Can you try with the 0.8.0 released yesterday ?

**Comment by LynxPantera** [comment]
Hello @jbpaux,
I just did a new deployment test with Terraform `0.12.3` and the Azure Stack `0.8.0` provider and I still have the same problem.

**Comment by jselleck** [comment]
We tested with 0.8.0 and have the same issue.

**Comment by bottkars** [comment]
Same here .

**Comment by jbpaux** [comment]
In that case, can you rename the title of the issue to 0.8.0 too ?
I haven't had the change to try it yet. Strugling to try to auth with azure-cli token in a disconnected env (the one you came for in Paris @bottkars 🤣 ).

**Comment by DinoBordonaro** [comment]
I see the same with 0.8.0 and Azure Stack Release 1906 on my Multinode System

**Comment by wellsluo** [comment]
Just want to check if there are any updates on this issue?

**Comment by cblackuk** [comment]
Would be awesome to know :-) so +1

**Comment by jbmcfarlin31** [comment]
Our primary resource handler is azure stack so this is hindering us quite a bit.. +1 on if there is any updates

**Comment by tombuildsstuff** [comment]
👋 

Thanks for opening this issue.

The Azure Stack instance that we have access to isn't currently running 1905 so we're not seeing this error in our tests unfortunately (but we're reaching out/working on this) - but taking a look into this (and comparing with AzureRM) I believe the casing on the Resource ID has changed for the Storage Account which means this is being parsed out as an empty string (which is why this errors being returned from the SDK).

Since unfortunately we don't have access to confirm that theory at this time (as our Azure Stack instance isn't running 1905) - so that we can diagnose this would anyone be able to confirm that the casing of the Resource ID segment `storageaccounts` has changed to `storageAccounts` using (for example) the Azure CLI on Azure Stack 1905?

Thanks!

**Comment by cblackuk** [comment]
@tombuildsstuff 

```powershell
ResourceGroupName      : system.xxxxxxxxx
StorageAccountName     : urphealthaccount
Id                     : /subscriptions/xxxxxx-xxxxx-xxxxx-xxxxx/resourcegroups/system.xxxxxxxx/providers/Microsoft.Storage/storageAccounts/urphealthaccount
Location               : xxxxxxxx
Sku                    : Microsoft.Azure.Management.Storage.Models.Sku
Kind                   : Storage
Encryption             : Microsoft.Azure.Management.Storage.Models.Encryption
AccessTier             :
CreationTime           : 01/02/2018 01:37:44
CustomDomain           : 
Identity               :
LastGeoFailoverTime    :
PrimaryEndpoints       : Microsoft.Azure.Management.Storage.Models.Endpoints
PrimaryLocation        : xxxxxxxx
ProvisioningState      : Succeeded
SecondaryEndpoints     :
SecondaryLocation      :
StatusOfPrimary        : Available
StatusOfSecondary      :
Tags                   :
EnableHttpsTrafficOnly : False
NetworkRuleSet         : 
Context                : Microsoft.WindowsAzure.Commands.Common.Storage.LazyAzureStorageContext
ExtendedProperties     : {}

```

So yeah ID is with uppercase A:
```powershell
Id                     : /subscriptions/xxxxxx-xxxxx-xxxxx-xxxxx/resourcegroups/system.xxxxxxxx/providers/Microsoft.Storage/storageAccounts/urphealthaccount
```

I hope that helps.

On Tenant side - same thing.

**Comment by tombuildsstuff** [comment]
@cblackuk thanks for confirming that - I believe #99 should fix this then 👍

**Comment by cblackuk** [comment]
Awesome!!! The PR looks legit, if that was the only issue it has got a chance to fix it :-)

Thanks @tombuildsstuff
