### ISSUE TITLE
Cannot apply terraform plan in v0.7.0 AND v0.8.0 using Client Secret key

### ISSUE THREAD

**Issue by jbmcfarlin31** [terraform-providers/terraform-provider-azurestack#98]
Using the azure stack provider version `0.8.0` and terraform version `0.11.14`, I get the following error when trying to plan and apply:
```
Error: Error running plan: 1 error occurred:
        * provider.azurestack: Unable to list provider registration status, it is possible that this is due to invalid credentials or the service principal does not have permission to use the Resource Manager API, Azure error: azure.BearerAuthorizer#WithAuthorization: Failed to refresh the Token for request to https://<endpoint_to_stack>/subscriptions/<sub_id>/providers?api-version=2016-02-01: StatusCode=0 -- Original Error: adal: Failed to execute the refresh request. Error = 'Post https://login.microsoftonline.com/.../oauth2/token?api-version=1.0: context canceled'
```

I have to forcefully `CTRL+C` out of the execution otherwise it just sits there and hangs. This originally started happening to me in version `0.7.0` of the stack provider as well. This works using version `0.6.0`, however, that becomes null and void with stack build 1905 in the relating issue mentioned in the issue here #90

**Comment by jbmcfarlin31** [comment]
Updating... tried using this with the azure stack provider version `0.8.1` that was just released and I am still seeing this same problem... I cannot provision against stack build 1905 and 1906.

**Comment by jbmcfarlin31** [comment]
@tombuildsstuff is there any update on when you might be able to upgrade your stack to 1905 and/or provide a patch for this? We are getting hit pretty hard with not being able to provision through terraform into our stack instance...

**Comment by jbmcfarlin31** [comment]
@thetonymaster @katbyte @tombuildsstuff Stack build 1907 is being deployed within the week... are there any updates on when this will be fixed? Thanks!

**Comment by jbmcfarlin31** [comment]
@tombuildsstuff @katbyte @cblackuk I managed to get around the initial authentication error by simply modifying the `go.mod` file and updating dependencies to their latest verisions...

The `go.mod` file looks like this now:
```module github.com/terraform-providers/terraform-provider-azurestack

go 1.12

require (
        github.com/Azure/azure-sdk-for-go v32.3.0+incompatible
        github.com/Azure/go-autorest v12.4.2+incompatible
        github.com/Azure/go-autorest/autorest v0.5.0
        github.com/Azure/go-autorest/autorest/adal v0.2.0
        github.com/davecgh/go-spew v1.1.1
        github.com/hashicorp/errwrap v1.0.0
        github.com/hashicorp/go-azure-helpers v0.5.0
        github.com/hashicorp/go-hclog v0.8.0 // indirect
        github.com/hashicorp/hil v0.0.0-20190212132231-97b3a9cdfa93 // indirect
        github.com/hashicorp/terraform v0.12.0
        github.com/terraform-providers/terraform-provider-azurerm v1.32.1
        golang.org/x/crypto v0.0.0-20190506204251-e1dfcc566284
)
```
Upon trying to build the binary, it failed as some function references were expecting `WaitForCompletionRef` instead of `WaitForCompletion`. After that the binary build was successful. 

Upon using it now, I run into an error with the storage container being created... This is what is being returned:
``` Error creating container "azsmytestsc" in storage account "azsmytestsa": storage: service returned error: StatusCode=400, ErrorCode=InvalidHeaderValue, ErrorMessage=The value for one of the HTTP headers is not in the correct format.
RequestId:cbd1f1e6-50ac-0c2d-5290-8cc0a7e7e814
Time:2019-08-08T21:35:59.4478718Z, RequestInitiated=Thu, 08 Aug 2019 21:35:59 GMT, RequestId=cbd1f1e6-50ac-0c2d-5290-8cc0a7e7e814, API Version=, QueryParameterName=, QueryParameterValue=
```

I traced that down into the `azurestack/resource_arm_storage_container.go` file, on line `112`. So I added some debug statements to see what was coming back, specifically for the `reference` variable on line `109` and the `createOptions` variable on within `checkContainerIsCreated`.

The `reference` variable showed the following:
```&{bsc:0xc00014c820 Name:azsmytestsc Properties:{LastModified: Etag: LeaseStatus: LeaseState: LeaseDuration: PublicAccess:} Metadata:map[] sasuri:{Scheme: Opaque: User:<nil> Host: Path: RawPath: ForceQuery:false RawQuery: Fragment:}}
```

The `createOptions` variable showed the following:
```&{Timeout:0 Access: RequestID:}```

Additional debug output:
``` [DEBUG] azurestack_storage_container.clusterstoragectr: apply errored, but we're indicating that via the Error pointer rather than returning it: Error creating container "azsmytestsc" in storage account "azsmytestsa": storage: service returned error: StatusCode=400, ErrorCode=InvalidHeaderValue, ErrorMessage=The value for one of the HTTP headers is not in the correct format.
RequestId:cbd1f1e6-50ac-0c2d-5290-8cc0a7e7e814
Time:2019-08-08T21:35:59.4478718Z, RequestInitiated=Thu, 08 Aug 2019 21:35:59 GMT, RequestId=cbd1f1e6-50ac-0c2d-5290-8cc0a7e7e814, API Version=, QueryParameterName=, QueryParameterValue=
```

```[ERROR] <root>: eval: *terraform.EvalApplyPost, err: Error creating container "azsmytestsc" in storage account "azsmytestsa": storage: service returned error: StatusCode=400, ErrorCode=InvalidHeaderValue, ErrorMessage=The value for one of the HTTP headers is not in the correct format.
RequestId:cbd1f1e6-50ac-0c2d-5290-8cc0a7e7e814
Time:2019-08-08T21:35:59.4478718Z, RequestInitiated=Thu, 08 Aug 2019 21:35:59 GMT, RequestId=cbd1f1e6-50ac-0c2d-5290-8cc0a7e7e814, API Version=, QueryParameterName=, QueryParameterValue=
2019/08/08 21:35:52 [ERROR] <root>: eval: *terraform.EvalSequence, err: Error creating container "azsmytestsc" in storage account "azsmytestsa": storage: service returned error: StatusCode=400, ErrorCode=InvalidHeaderValue, ErrorMessage=The value for one of the HTTP headers is not in the correct format.
RequestId:cbd1f1e6-50ac-0c2d-5290-8cc0a7e7e814
Time:2019-08-08T21:35:59.4478718Z, RequestInitiated=Thu, 08 Aug 2019 21:35:59 GMT, RequestId=cbd1f1e6-50ac-0c2d-5290-8cc0a7e7e814, API Version=, QueryParameterName=, QueryParameterValue=
```

I am learning go, so the code is very new to me... but it kind of looks like the problem exists in the `create` method that resides on the [azure-sdk-for-go](https://github.com/Azure/azure-sdk-for-go/blob/530645103ffb176d64b5385336579a7517661a55/storage/container.go#L278)

Please advise...

**Comment by jbmcfarlin31** [comment]
@tombuildsstuff Just to update... I restarted over with the current master repo and started only upgrading one dependency at a time to try and retain current functionality, but get passed the authentication error as described aboved. I managed to succeed...

You will need to change the `github.com/Azure/azure-go-autorest` version to be as follows:
```
module github.com/terraform-providers/terraform-provider-azurestack

go 1.12

require (
        contrib.go.opencensus.io/exporter/ocagent v0.5.0 // indirect
        github.com/Azure/azure-sdk-for-go v30.0.0+incompatible
        github.com/Azure/go-autorest v12.0.0+incompatible
        github.com/davecgh/go-spew v1.1.1
        github.com/dnaeon/go-vcr v1.0.1 // indirect
        github.com/hashicorp/errwrap v1.0.0
        github.com/hashicorp/go-azure-helpers v0.3.2
        github.com/hashicorp/go-hclog v0.8.0 // indirect
        github.com/hashicorp/hcl v1.0.0 // indirect
        github.com/hashicorp/hil v0.0.0-20190212132231-97b3a9cdfa93 // indirect
        github.com/hashicorp/terraform v0.12.0
        github.com/terraform-providers/terraform-provider-azurerm v1.15.0
        golang.org/x/crypto v0.0.0-20190426145343-a29dc8fdc734
)
```
This will allow the adal piece (I believe) to be upgraded to the latest versions, but retain the current functionality. At least this was the case for me. When I made the change and ran `make build`, I got an error with the same `WaitForCompletion` reference. You will need to modify the following files:
1) `azurestack/resource_arm_resource_group.go` 
2) `azurestack/resource_arm_virtual_machine_scale_set.go`

Change the `WaitForCompletion` to `WaitForCompletionRef` and rerun `make build`. This will allow the binary to built and can be used.

I successfully deployed my existing infrastructure (with the exception of re-working some config code for terraform v12).

Hope this helps others!

**Comment by jbpaux** [comment]
Hi @jbmcfarlin31 I tried your changes but still no luck with terraform plan. Same error.
Did you do other changes ? Do you have working branch on your fork ?
Did you do some special steps before make build ? (I did a go mod tidy/go mod vendor)

**Comment by jbmcfarlin31** [comment]
@jbpaux my current branch is one where I was making a ton of changes (upgrading all the dependencies) and ran into the storage container problem. I then re-cloned the master repo here and began changing single dependencies. Keep in mind I am running on azure stack build `1907` but this should work for `1905` and `1906`.

What errors are you seeing that is preventing you to plan? Some things I noticed when I was working through this (and this might be because I am not entirely sure how go works) but when you upgrade and change things I guess go stores it in a cache and that was causing me some odd things. 

I would try the following if you haven't already:
1) re-clone this master repo
2) modify the `go.mod` file and change the auto-rest dependency to be `v12.0.0+incompatible`.
3) run `make fmt` and then run `make build` and see what happens... it should fail the build and get an error saying `WaitForCompletion is undefined` in which you need to modify the two files that is is failing on by changing the `WaitForCompletion` to `WaitForCompletionRef`.
4) After modifying, re-run `make fmt` and then re-run `make build` - this should work, as that is all I had to change

If the `make build` was successful and you did not run into any errors, you will need to navigate to your terraform working directory (where all your `*.tf` files reside), and do the following:
1) `mkdir terraform.d/plugins/linux_amd64` - if you don't have one already
2) `cp $GOPATH/bin/terraform-azurestack-provider terraform.d/plugins/linux_amd64/` - this is copying the newly created binary for the stack provider that `make build` generated into a terraform directory that is checked first prior to searching for it online.
3) re-run `terraform init` (NOTE: If you have previously built in this directory e.g. `terraform init/plan/apply` you will need to erase the `.terraform/` directory to ensure a fresh clean state)
4) re-run `terraform plan`
5) re-rerun `terraform apply`

Hope this helps, let me know if it doesn't and I can try and help further!

**Comment by katbyte** [comment]
Hi @jbmcfarlin31,

Just a heads up we have upgraded stack to a more recent autorest & SDK version. Could you potentially give it a try and see if it fixes this issue? thanks!

**Comment by jbpaux** [comment]
solved for me. Thank you !

**Comment by jbmcfarlin31** [comment]
@katbyte this looks to have fixed our issue and I no longer need to use my own patch. Version `0.9.0` seems to be the one!

**Comment by katbyte** [comment]
Awesome! great to hear it
